# Generated by Django 4.2.1 on 2023-05-22 15:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveBigIntegerField(verbose_name='Quantity')),
                ('type', models.CharField(choices=[('1', 'stock-in'), ('0', 'stock-out')], max_length=12, verbose_name='Type')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
                'db_table': 'History',
                'ordering': ['date_created'],
            },
        ),
    ]
