# Generated by Django 4.2.2 on 2023-06-08 18:25

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(verbose_name='Category description')),
                ('status', models.CharField(choices=[('0', 'Stack-out'), ('1', 'Stack-in')], default='0', max_length=10, verbose_name='Category status')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Product Image')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(verbose_name='Product description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[core.models.min_value_validator], verbose_name='Product price')),
                ('status', models.CharField(choices=[('0', 'Stack-out'), ('1', 'Stack-in')], default='0', max_length=10, verbose_name='Product status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='core.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveBigIntegerField(default=0, validators=[core.models.min_value_validator], verbose_name='Product Quantity')),
                ('type', models.CharField(choices=[('0', 'Stack-out'), ('1', 'Stack-in')], default='0', max_length=20)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'db_table': 'Stock',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveBigIntegerField(verbose_name='Quantity')),
                ('type', models.CharField(choices=[('1', 'stock-in'), ('0', 'stock-out')], max_length=12, verbose_name='Type')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
                'db_table': 'History',
                'ordering': ['date_created'],
            },
        ),
    ]
