# Generated by Django 4.2.2 on 2023-06-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productseller_remove_product_image_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ManyToManyField(blank=True, to='core.productseller'),
        ),
    ]
